name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  
  pull-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mlops:latest
      - name: Run Docker container and Test Model
        run: |
          OUTPUT=$(docker run mlops python test.py)

          echo "Score:"

          echo "$OUTPUT"

          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
