name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Job
        run: echo "This is a dummy job, no actual actions are performed."

  pull-and-test:
    needs: dummy-job  # Ensure the dummy job runs first
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mlops:latest

      - name: Run Docker container and Test Model
        run: |
          OUTPUT=$(docker run ${{ secrets.DOCKER_USERNAME }}/mlops:latest python test.py)

          echo "Score:"
          echo "$OUTPUT"

          if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then 
            echo "Insufficient Accuracy" && exit 1 
          fi

